version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development

  test:
    build: .
    volumes:
      - .:/code
    command: sh -c "python -m unittest /home/arunvikram/Documents/mycrud/Tests/testmock.py"
